### ISSUE TITLE
Existing RTE configuration will not be pulled

### ISSUE THREAD

**Issue by Epoche-Napoleon** [netresearch/t3x-cowriter#15]
System requirements: 
TYPO3 11.5.25
t3_cowriter 1.2.1

After I extended my existing RTE configuration according to the instructions, my original RTE configurations don't work anymore.

It looks like this error repeats itself with a new installation:
https://github.com/netresearch/t3-cowriter/pull/13xisting RTE configuration according to the instructions, my original RTE configurations don't work anymore.

**Comment by Gitsko** [comment]
HI @Epoche-Napoleon,

if you have your own RTE config you only have to add it as written in the README under point 4 (point 3 you have to leave out):
```
imports:
  - { resource: "EXT:t3_cowriter/Configuration/RTE/Plugin.yaml" }

editor:
  externalPlugins:
    cowriter:
      resource: "EXT:t3_cowriter/Resources/Public/JavaScript/Plugins/cowriter/"
```

What exactly have you configured ?
